#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
KEYCHAIN_SERVICE=bio.bioredox.buzz.nsec
KEYCHAIN_ACCOUNT=$(id -un)
API_ENDPOINT=https://knowledge.bioredox.bio:8444
CONFIG_FILE="${SCRIPT_DIR}/mcp/local-config.json"
UPLOAD_ROOT="${HOME}/BioRedox Knowledge Uploads"

keychain_npub() {
  /usr/bin/security find-generic-password \
    -s "${KEYCHAIN_SERVICE}" \
    -a "${KEYCHAIN_ACCOUNT}" \
    -w 2>/dev/null \
    | uv run --quiet --with 'nostr-sdk==0.44.2' python -c \
      'import sys; from nostr_sdk import Keys; print(Keys.parse(sys.stdin.read().strip()).public_key().to_bech32())' \
      2>/dev/null
}

command -v uv >/dev/null 2>&1 || {
  warn "uv is required before this setup can continue."
  exit 1
}
[[ "$(uname -s)" == "Darwin" ]] || {
  warn "This setup requires the macOS Keychain."
  exit 1
}

banner "BioRedox Knowledge MCP setup"

stage "Confirm the Buzz public identity"
say "Use the same public identity that you use for Buzz."
ask EXPECTED_NPUB "Paste your Buzz npub:"
if [[ ! "${EXPECTED_NPUB}" =~ ^npub1[023456789acdefghjklmnpqrstuvwxyz]+$ ]]; then
  warn "The value is not a valid npub format."
  exit 1
fi

stage "Verify the matching private key"
say "The value stays in this local process and is not written to a file."
ask_secret BUZZ_NSEC "Paste the matching Buzz nsec:"
DERIVED_NPUB=$(printf '%s' "${BUZZ_NSEC}" | uv run --quiet --with 'nostr-sdk==0.44.2' python -c 'import sys; from nostr_sdk import Keys; print(Keys.parse(sys.stdin.read().strip()).public_key().to_bech32())')
if [[ "${DERIVED_NPUB}" != "${EXPECTED_NPUB}" ]]; then
  unset BUZZ_NSEC
  warn "The nsec does not match the Buzz npub. Nothing was stored."
  exit 1
fi
unset BUZZ_NSEC DERIVED_NPUB
say "The key pair matches."

stage "Store the key in the local macOS Keychain"
if /usr/bin/security find-generic-password -s "${KEYCHAIN_SERVICE}" -a "${KEYCHAIN_ACCOUNT}" >/dev/null 2>&1; then
  if ! STORED_NPUB=$(keychain_npub); then
    warn "The existing Keychain item is not a valid Nostr key. Nothing was changed."
    exit 1
  fi
  if [[ "${STORED_NPUB}" != "${EXPECTED_NPUB}" ]]; then
    warn "A different key already uses this Keychain service. Nothing was changed."
    exit 1
  fi
  say "The matching key is already in this Mac's login Keychain."
else
  say "The Keychain will ask for the same nsec again with hidden input."
  if ! confirm "Store the key only in this Mac's login Keychain?"; then
    warn "No key was stored."
    exit 1
  fi
  /usr/bin/security add-generic-password \
    -a "${KEYCHAIN_ACCOUNT}" \
    -s "${KEYCHAIN_SERVICE}" \
    -l "BioRedox Buzz signing key" \
    -w
  if ! STORED_NPUB=$(keychain_npub); then
    /usr/bin/security delete-generic-password -s "${KEYCHAIN_SERVICE}" -a "${KEYCHAIN_ACCOUNT}" >/dev/null
    warn "The new Keychain item was invalid, so the setup removed it."
    exit 1
  fi
  if [[ "${STORED_NPUB}" != "${EXPECTED_NPUB}" ]]; then
    /usr/bin/security delete-generic-password -s "${KEYCHAIN_SERVICE}" -a "${KEYCHAIN_ACCOUNT}" >/dev/null
    warn "The stored key did not match. The new Keychain item was removed."
    exit 1
  fi
fi
unset STORED_NPUB EXPECTED_NPUB

stage "Install and configure the local MCP"
mkdir -p "${UPLOAD_ROOT}"
chmod 700 "${UPLOAD_ROOT}"
printf '{\n  "api_url": "%s",\n  "keychain_account": "%s",\n  "upload_root": "%s"\n}\n' \
  "${API_ENDPOINT}" "${KEYCHAIN_ACCOUNT}" "${UPLOAD_ROOT}" > "${CONFIG_FILE}"
chmod 600 "${CONFIG_FILE}"
UV_BIN=$(command -v uv)
if command -v codex >/dev/null 2>&1; then
  if codex mcp get bioredox-knowledge >/dev/null 2>&1; then
    codex mcp remove bioredox-knowledge >/dev/null
  fi
  codex mcp add bioredox-knowledge -- \
    "${UV_BIN}" run "${SCRIPT_DIR}/mcp/server.py" >/dev/null
  say "The MCP is registered for the local Codex host."
else
  SKIPPED+=("Codex MCP registration (install Codex, then run this setup again)")
  warn "Codex is not installed, so its MCP registration was skipped."
fi
say "The public local configuration is ready."
say "Place approved source files in ${UPLOAD_ROOT} before ingestion."

stage "Run a signed health check"
say "This request proves the network route, signature, allowlist, API, and Qdrant."
uv run "${SCRIPT_DIR}/mcp/health_check.py"

finish
